# Generated by Django 5.2.4 on 2025-10-31 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['room_no', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], help_text='Month of the reading (1=Jan, 12=Dec)')),
                ('year', models.IntegerField()),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_units', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('calculated_bill', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_readings', to='app.tenant')),
            ],
            options={
                'verbose_name': 'Electricity Reading',
                'verbose_name_plural': 'Electricity Readings',
                'ordering': ['year', 'month', 'tenant__room_no'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'month', 'year'), name='unique_reading_per_month_year')],
            },
        ),
    ]
