# Generated by Django 5.2.4 on 2025-11-01 13:18

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_expensecategory_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricityreading',
            options={'ordering': ['-year', '-month', 'tenant__room_no']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.AlterField(
            model_name='electricityreading',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='electricityreading',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='electricityreading',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='app.tenant'),
        ),
        migrations.AlterField(
            model_name='electricityreading',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='year',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='joining_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='room_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
