# Generated by Django 5.2.4 on 2025-11-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_electricityreading_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityreading',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_readings', to='app.tenant'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_expenses', to='app.expensecategory'),
        ),
    ]
